---
title: "Daughters"
author: "Enxhi Buxheli and John LaVelle"
date: "2/2/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment=NA)

# Attaching necessary libraries
library(tidyverse)
library(dplyr)
library(janitor)
library(knitr)
library(kableExtra)
# library(gt)

# Global option used in table to replace NAs with '-' for aesthetics
options(knitr.kable.NA = '-')

# Loading in the data

# taken from given replication file
# library(Zelig)
# library("ZeligChoice") 
library(xtable)
# library(reshape)
# library(apsrtable)
library(stargazer)
# library(rms)

```
```{r xtable, results="asis"}

# garbage to be deleted
# sim <- Zelig:::sim

# garbage to be deleted
# cl   <- function(dat,fm, cluster){
#            require(sandwich, quietly = TRUE)
#            require(lmtest, quietly = TRUE)
#            M <- length(unique(cluster))
#            N <- length(cluster)
#            K <- fm$rank
#            dfc <- (M/(M-1))*((N-1)/(N-K))
#            uj  <- apply(estfun(fm),2, function(x) tapply(x, cluster, sum));
#            vcovCL <- dfc*sandwich(fm, meat=crossprod(uj)/N)
#            coeftest(fm, vcovCL) }
           
case_data  <- read_csv("dataverse_files/glynn_sen_daughters_by_case_1.csv") %>% clean_names()
judge_data <- read_csv("dataverse_files/glynn_sen_daughters_by_judge.csv") %>% clean_names()
           


########################################################
## Loading the Data
########################################################

## This loads three data sets
## 1. Gender cases
## 2. Cleaned by-judge data
## 3. Non-gender cases, downloaded from Kuersten and Haire's website
## (Commented out; their data are available from their website)

# ## Gender cases only
# ## Removing male plaintiffs:
 women_cases <- subset(case_data, femplaintiff == 1)

 women_cases <- subset(women_cases, (area %in% c("employment", "Title IX", "pregnancy", "abortion", "reproductive rights")))

 women_cases$area <- factor(women_cases$area, levels = c("abortion","employment","pregnancy","reproductive rights","Title IX"))

# this is the intro to the reading in of the case file
# ## All cases, including non-gender cases (from Ashlyn Kuersten/Susan Haire's coding)
# cases <- read.csv("cases.for.analysis.csv")	

 # NOTE: think of better name for this variable than "all"
all <- subset(judge_data, girls != "NaN") # subsets judge
								  # data to those for 
								  # whom we have fertility data

```
```{r, results="asis"}
######################################################
## Table 1: Number of children and girls
######################################################

## garbage to be deleted
# aa <- table(all$republican, all$child)
# bb <- table(all$republican, all$girls)
# 
# ## and now for the table:
# 
# xtable(aa)
# xtable(bb)


# Table 1: Number of Children and Girls for U.S. Courts of Appeals Judges 
#          Participating in Gender-Related Cases, 1996-2002
# Here we are keeping the # of children, # of girls, & party affiliation and
# building a count table. Additionally, here the party name is recoded to be
# more friendly to a reader of the table ("Republicans" and "Democrats")
t1 <- select(judge_data,
              child, girls, republican) %>% 
  filter(child < 10, girls < 10) %>% 
  mutate(party = ifelse(1 == republican, "Republicans", "Democrats"))


# Number of Children portion of the table
t1_child <- t1 %>% 
  count(party, child) %>% 
  spread(child, n) %>% 
  adorn_totals("col")

# Number of Girls portion of the table
t1_girls <- t1 %>% 
  count(party, girls) %>% 
  spread(girls, n)

# Binding the rows to create one table with girls and children
t1_combined <- bind_rows(t1_child, t1_girls) %>% 
  kable("latex", booktabs = TRUE) %>% 
  column_spec(1, bold = TRUE)

# Styling the table to make it look like the original figure
t1_combined %>% 
  group_rows("Number of Children", 1, 2, bold = TRUE) %>% 
  group_rows("Number of Girls", 3, 4, hline_before = T)


```

```{r, results="asis"}
########################################################
## Table 2: Judge Demographics
########################################################

dems <- subset(all, republican == 0)
reps <- subset(all, republican == 1)
women <- subset(all, woman == 1)
men <- subset(all, woman == 0)


mean.kids <-  cbind(mean(na.omit(all$child)), 
		mean(na.omit(dems$child)),
		mean(na.omit(reps$child)),
		mean(na.omit(women$child)),
		mean(na.omit(men$child))
	)

mean.girls <- cbind(mean(na.omit(all$girls)), 
		mean(na.omit(dems$girls)),
		mean(na.omit(reps$girls)),
		mean(na.omit(women$girls)),
		mean(na.omit(men$girls))
	)

prop.zero <- cbind(prop.table(table(na.omit(all$child)))[1],
prop.table(table(na.omit(dems$child)))[1],
prop.table(table(na.omit(reps$child)))[1],
prop.table(table(na.omit(women$child)))[1],
prop.table(table(na.omit(men$child)))[1]
	)
	
	
prop.one <- cbind(prop.table(table(na.omit(all$child)))[2],
prop.table(table(na.omit(dems$child)))[2],
prop.table(table(na.omit(reps$child)))[2],
prop.table(table(na.omit(women$child)))[2],
prop.table(table(na.omit(men$child)))[2]
	)
	
prop.two <- cbind(prop.table(table(na.omit(all$child)))[3],
prop.table(table(na.omit(dems$child)))[3],
prop.table(table(na.omit(reps$child)))[3],
prop.table(table(na.omit(women$child)))[3],
prop.table(table(na.omit(men$child)))[3]
	)

prop.three <- cbind(prop.table(table(na.omit(all$child)))[4],
prop.table(table(na.omit(dems$child)))[4],
prop.table(table(na.omit(reps$child)))[4],
prop.table(table(na.omit(women$child)))[4],
prop.table(table(na.omit(men$child)))[4]
	)

prop.four <- cbind(prop.table(table(na.omit(all$child)))[5],
prop.table(table(na.omit(dems$child)))[5],
prop.table(table(na.omit(reps$child)))[5],
prop.table(table(na.omit(women$child)))[5],
prop.table(table(na.omit(men$child)))[5]
	)

prop.five <- cbind(prop.table(table(na.omit(all$child)))[6],
prop.table(table(na.omit(dems$child)))[6],
prop.table(table(na.omit(reps$child)))[6],
prop.table(table(na.omit(women$child)))[6],
prop.table(table(na.omit(men$child)))[6]
	)
	
aa <- table(na.omit(all$child))
	plus6.all <- sum(aa[7:length(aa)])/sum(aa)
	
bb <- table(na.omit(dems$child))
	plus6.dems <- sum(bb[7:length(bb)])/sum(bb)

cc <- table(na.omit(reps$child))
	plus6.reps <- sum(cc[7:length(cc)])/sum(cc)

dd <- table(na.omit(women$child))
	plus6.women <- sum(dd[7:length(dd)])/sum(dd)

ee <- table(na.omit(men$child))
	plus6.men <- sum(ee[7:length(ee)])/sum(ee)
	
prop.six.or.greater <- cbind(plus6.all, plus6.dems, plus6.reps, plus6.women, plus6.men)
	
mean.female <- cbind(mean(na.omit(all$woman)), 
		mean(na.omit(dems$woman)),
		mean(na.omit(reps$woman)),
		mean(na.omit(women$woman)),
		mean(na.omit(men$woman))
	)
	
mean.rep <- cbind(mean(na.omit(all$republican)), 
		mean(na.omit(dems$republican)),
		mean(na.omit(reps$republican)),
		mean(na.omit(women$republican)),
		mean(na.omit(men$republican))
)


mean.white <- cbind(mean(na.omit(all$race == 1)), 
		mean(na.omit(dems$race == 1)),
		mean(na.omit(reps$race == 1)),
		mean(na.omit(women$race == 1)),
		mean(na.omit(men$race == 1))
	)

mean.yearb <- cbind(mean(na.omit(all$yearb)), 
		mean(na.omit(dems$yearb)),
		mean(na.omit(reps$yearb)),
		mean(na.omit(women$yearb)),
		mean(na.omit(men$yearb))
	)

no_judges <- cbind(nrow(all), nrow(dems), nrow(reps), nrow(women), nrow(men))

demographic_table <- rbind(mean.kids, mean.girls, prop.zero, prop.one,
	prop.two, prop.three, prop.four, prop.five, prop.six.or.greater, mean.female, mean.rep, mean.white, mean.yearb, no_judges)

colnames(demographic_table) <- c("All", "Democrats", "Republicans","Women", "Men")
rownames(demographic_table) <- c("Mean No. Children", "Mean No. Girls",
	"Proportion who have 0 children","1 children",
	"2 children", "3 children",
	"4 children", "5 Children", "6 Children or More", "Proportion Female", "Proportion Republican",
	"Proportion White", "Mean Year Born", "N")
xtable(demographic_table, digits = 2, caption = "Demographics of U.S. Court of Appeal Judges who voted on gender-related cases (1996-2002)", label = "t:statsgender", align = "l|ccccc")

########################################################
## Calculating the Weights (Number of Cases)
########################################################

no_cases <- matrix(data = NA, nrow = nrow(judge_data), ncol = 1)
for(i in 1:length(no_cases)){
	no_cases[i] <- nrow(women_cases[which(women_cases$name == judge_data$name[i]),])
	}

judge_data <- cbind(judge_data, no_cases)

## total number of cases we are working with

sum(judge_data$no_cases) 	# should be 2,674 reported in the paper

########################################################
## Calculating the Outcome Var
########################################################

no_liberalvote <- matrix(data = NA, nrow = nrow(judge_data), ncol = 1)
for(i in 1:length(no_liberalvote)){
	stuff <- women_cases[which(women_cases$name == judge_data$name[i]),]
	no_liberalvote[i] <- nrow(subset(stuff, vote == 2 | vote == 3))
	}

lib_vote_share <- no_liberalvote/no_cases

judge_data <- cbind(judge_data, no_liberalvote, lib_vote_share)
judge_data <- subset(judge_data, girls != "NaN")

########################################################
## Subsetting Data to Various Populations (for use later)
########################################################

## just women:
women.means <- subset(judge_data, woman == 1)

## just men:
men.means <- subset(judge_data, woman == 0)

## just republicans:
rep.means <- subset(judge_data, republican == 1)

## just democrats
dem.means <- subset(judge_data, republican == 0)


#######################################################
## Figure 1
########################################################

#pdf(file= "lib_votes.pdf", width = 5, height = 5, family = "Helvetica", pointsize = 10)
plot(density(judge_data$lib_vote_share), 
	xlim = c(-.4,1.4), ylim = c(0,2.5),
	ylab = "", xlab = "Proportion of Cases Decided in a Feminist Direction", 
	yaxt = "n", 
	bty = "n", 
	main = "",
	col = "black", lwd = 2)
lines(density(rep.means$lib_vote_share), 
	col = "firebrick", lwd = 2, lty  = 2)
lines(density(dem.means$lib_vote_share), 
	col = "dodgerblue", lwd = 2, lty  = 3)
abline(v = .5, col = "grey50", lty = 2)
text(x = .5, y = 2.4, "Less Feminist", col = "grey50", pos = 2, cex = 0.9)
text(x = .5, y = 2.4, "More Feminist", col = "grey50", pos = 4, cex = 0.9)
text(x = .25, y = 1.7, "Republicans", pos = 2, cex = 0.9)
text(x = .7, y = 1, "Democrats", pos = 4, cex = 0.9)
text(x = .075, y = .6, "All", pos = 4, cex = 0.9)
#dev.off()


```


```{r, results="asis"}


#######################################################
## Table 3: Distribution of Cases
########################################################

gg <- rbind (summary(judge_data$no_cases), summary(dem.means$no_cases), summary(rep.means$no_cases))
rownames(gg) <- c("All Judges", "Democrats", "Republicans")
xtable(gg, caption = "Distribution of the number of gender-related cases heard per judge, 1996-2002.", label = "t:number_cases1")


```

```{r stargazer, results = "asis"}
########################################################
## Table 4: Core Results (WLS) 
########################################################

## Note from John: had to change as.factor(circuit.1) to as.factor(circuit_1), 
# because of the way that Zelig changed how they handle renaming duplicate 
# columns of info

################ Results for all judges

#judge_data <- subset(judge_data, child > 0)

mod1 <- lm(lib_vote_share ~ as.factor(girls) + as.factor(child), 
	data = judge_data, weights = judge_data$no_cases)

mod2 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child), 
	data = judge_data, weights = judge_data$no_cases)

mod3 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3), 
	data = judge_data, weights = judge_data$no_cases)

mod4 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit_1), 
	data = judge_data, weights = judge_data$no_cases)
		
################ Results for judges between 1 and 4 children
	
mod5 <- lm(lib_vote_share ~ as.factor(girls) + as.factor(child), 
	data = subset(judge_data, child < 5 & child > 0), weights = judge_data$no_cases[which(judge_data$child > 0 & judge_data$child < 5)])

mod6 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child), 
	data = subset(judge_data, child < 5 & child > 0), weights = judge_data$no_cases[which(judge_data$child > 0 & judge_data$child < 5)])

mod7 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3), 
	data = subset(judge_data, child < 5 & child > 0), weights = judge_data$no_cases[which(judge_data$child > 0 & judge_data$child < 5)])

mod8 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit_1), 
	data = subset(judge_data, child < 5 & child > 0), weights = judge_data$no_cases[which(judge_data$child > 0 & judge_data$child < 5)])

stargazer(mod1, mod2, mod3, mod4, mod5, mod6, mod7, mod8, header = FALSE,
	style = "ajps", omit.stat = c("f","ser"), dep.var.labels = "Weighted least squares results, gender cases only. Outcome is proportion of feminist votes.  Models 1--4 are for all judges, while Models 5--8 are for judges with 1--4 children.  (No judge among those with 1--4 children had four girls.) All models include fixed effects for number of children and use weights based on the number of cases heard by each judge.", digits = 2, omit = c("circuit"), covariate.labels = c("1 Girl","2 Girls","3 Girls","4 Girls","5 Girls","At Least 1 Girl",	
	"1 Child","2 Children","3 Children","4 Children","5 Children","6 Children","7 Children","8 Children",
	"9 Children","Republican","Age at Investiture","Catholic","Woman","African American","Hispanic","Constant"))
```

```{r, results="asis"}
#######################################################
## Table 5: Core Results (Case-Level)
#######################################################

# DO ALL EXCEPT COLUMN 6 OF THIS ONE
# also had problems but might not be so bad -> look at filtering and selecting?

# it seems like Mark suggested that we do this one using the built in 
# packages, instead of using this Zelig code.


wom_cases <- case_data %>% filter(femplaintiff == 1, area %in% c("employment", "Title IX", "pregnancy", "abortion", "reproductive rights"), child < 5 & child > 0) %>% 
  mutate(area = factor(area, c("abortion", "employment", "pregnancy", "reproductive rights", "Title IX")))


mod_7 <- glm(progressive_vote ~ as.factor(girls) + as.factor(child), data = wom_cases, family = binomial)
mod_8 <- glm(progressive_vote ~ I(girls > 0) + as.factor(child), data = wom_cases, family = binomial)
mod_9 <- glm(progressive_vote ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit) + as.factor(year), data = wom_cases, family = binomial)
mod_10 <- glm(progressive_vote ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race == 3) + as.factor(circuit) + as.factor(year) + as.factor(area), data = wom_cases, family = binomial)
mod_11 <- glm(progressive_vote ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race == 3) + as.factor(circuit) + as.factor(year) + as.factor(area), data = wom_cases, family = binomial)


stargazer(type = "latex", mod_7, mod_8, mod_9, mod_10, mod_11, header = FALSE, var.labels = "Logit and ordered logit results, gender cases only. Outcome is whether judge in a case votes in a feminist direction (Columns 1--5) or in a conservative, moderate, or liberal direction (Column 6).  All models include fixed effects for total number of children and Columns 3--6 include circuit and year fixed effects. Column 5 additionally includes standard errors clustered at the case level", covariate.labels = c("1 Girl","2 Girls","3 Girls","At Least 1 Girl",
	"2 Children","3 Children","4 Children","Republican","Age at Investiture","Catholic","Woman",	
	"African American","Hispanic", "10th Cir", "11th Cir","2nd Cir","3rd Cir",
	"4th Cir","5th Cir","6th Cir","7th Cir","8th Cir","9th Cir","DC","1997","1998","1999","2000","2001","2002",
	"Employment","Pregnancy","Reproduction","Title IX","Constant"),digits = 2)

# # my.out7 <- zelig(progressive.vote ~ as.factor(girls) + as.factor(child), 
# # 		model = "logit", data = subset(women_cases, child < 5 & child > 0))
# # summary(my.out7)
# # 
# # my.out8 <- zelig(progressive.vote ~ I(girls > 0) + as.factor(child), 
# # 		model = "logit", data = subset(women_cases, child < 5 & child > 0))
# # summary(my.out8)
# # 
# # my.out9 <- zelig(progressive.vote ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit) + as.factor(year), 
# # 		model = "logit", data = subset(women_cases, child < 5 & child > 0))
# # summary(my.out9)
# # 
# # my.out10 <- zelig(progressive.vote ~ I(girls>0) + as.factor(child) + republican 
# # 	+ age + I(religion == 4) + woman + I(race == 2) + I(race == 3) + as.factor(circuit) + as.factor(year) 
# # 	+ as.factor(area), data = subset(women_cases, child < 5 & child > 0), model = "logit")
# # summary(my.out10)
# # 
# # ## including clustered standard errors at the case level (bootstrap)
# # 
# # my.out11 <- zelig(progressive.vote ~ I(girls>0) + as.factor(child) + republican 
# # 	+ age + I(religion == 4) + woman + I(race == 2) + I(race == 3) + as.factor(circuit) + as.factor(year) 
# # 	+ as.factor(area), 
# # 	data = subset(women_cases, child < 5 & child > 0), model = "logit")
# # 
# # ## Note: Running the ordered logit with polr, in subsetting the data, there are some case areas
# # ## in which there are no observations. Those coefficients are being dropped at POLR gives an
# # ## warning. Nothing to worry.
# # 
# # my.out12 <- zelig(as.factor(vote) ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit) + as.factor(year) + as.factor(area), 
# #                   model = "ologit", data = subset(women_cases, child < 5 & child > 0))
# # summary(my.out12)
# # 
# # ## Now: Calculating standard errors bootstrapped at the case level:
# # ## Note: This takes about 10 minutes to run. 
# # 
# # ## Grab the data for these two models
# # mod12 <- as.formula("~ progressive.vote + vote + girls +  child + republican +race + age + religion + woman + circuit + year + area + casename")
# # dat12 <- model.frame(mod12, data = subset(women_cases, child < 5 & child > 0))
# # dat12$casename <- as.character(dat12$casename)
# 
# ## Create list of data.frames for each case for easy reference
# casenames <- sort(unique(dat12$casename))
# caselist <- lapply(casenames, function(x) dat12[which(dat12$casename == x),])
# names(caselist) <- casenames
# 
# ## Running the bootstraps
# ## Note that not all of the coefficients will be sampled in any given of the 
# ## bootstraps - this might result in some warnings form polr
# ## (the ordered logit), but is not a problem for the results
# 
# boots <- 1000
# b.star11 <- matrix(NA, ncol =length(my.out11$result$coef), nrow = boots)
# colnames(b.star11) <- names(my.out11$result$coef)
# b.star12 <- matrix(NA, ncol =length(my.out12$result$coef), nrow = boots)
# colnames(b.star12) <- names(my.out12$result$coef)
# set.seed(1234)
# for (b in 1:boots) {
# 	if ((b%%10) == 0) cat("boot: ", b, "\n")
# 	clust.sample <- sample(casenames, replace = TRUE)
# 	c.boot <- do.call(rbind,lapply(clust.sample,function(x) caselist[[x]]))
# 	out11.star <- glm(progressive.vote ~ I(girls>0) + as.factor(child) + republican 
# 	+ age + I(religion == 4) + woman + I(race == 2) + I(race == 3) + as.factor(circuit) + as.factor(year) + as.factor(area), data = c.boot, family = binomial("logit"))
#     out12.star <- polr(as.factor(vote) ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit) + as.factor(year) + as.factor(area), data = c.boot)	
#   b.star11[b,names(out11.star$coef)] <- out11.star$coef
# 	b.star12[b,names(out12.star$coef)] <- out12.star$coef
# 		}
# bcse11 <- apply(b.star11, 2, sd, na.rm=TRUE)		
# bcse12 <- apply(b.star12, 2, sd, na.rm=TRUE)		
# #save(list=c("bcse11", "bcse12"), file = "bootstraps.RData")
# ## End bootstrap code here
# 

## can re-load bootstraped data to avoid having to run previous code
## load("bootstraps.RData")

## Replacing the normal SEs with the bootstrap SEs for the final Table 5
# stargazer(my.out7, my.out8, my.out9, my.out10, my.out11, my.out12, 
# 	style = "ajps", omit.stat = c("f","ser"), dep.var.labels = "Logit and ordered logit results, gender cases only. Outcome is whether judge in a case votes in a feminist direction (Columns 1--5) or in a conservative, moderate, or liberal direction (Column 6).  All models include fixed effects for total number of children and Columns 3--6 include circuit and year fixed effects. Column 5 additionally includes standard errors clustered at the case level", covariate.labels = c("1 Girl","2 Girls","3 Girls","At Least 1 Girl",
# 	"2 Children","3 Children","4 Children","Republican","Age at Investiture","Catholic","Woman",	
# 	"African American","Hispanic", "10th Cir", "11th Cir","2nd Cir","3rd Cir",
# 	"4th Cir","5th Cir","6th Cir","7th Cir","8th Cir","9th Cir","DC","1997","1998","1999","2000","2001","2002",
# 	"Employment","Pregnancy","Reproduction","Title IX","Constant"),se = list(my.out7 = NULL, my.out8 = NULL, my.out8 = NULL, my.out10 = NULL,my.out11 = bcse11, my.out12 = bcse12), digits = 2)
# 
# 

#######################################################
## Table 6: Comparison for Non-Gender Related Cases
#######################################################

# WE DO NOT DO THIS ONE

```
```{r, results="asis"}
########################################################
## Table 7: Dividing Up the Sample
########################################################

## First, limiting sample space to only judges 
## with 1-4 kids 
#(there is only 1 judge with no girls conditional on 5 or more kids)

#judge_data <- subset(judge_data, child < 5 & child > 0)
rep.means <- subset(rep.means, child < 5 & child > 0)
dem.means <- subset(dem.means, child < 5 & child >0)
men.means <- subset(men.means, child < 5 & child > 0)
women.means <- subset(women.means, child < 5 & child > 0)

## and then by case
rep.cases <- subset(women_cases, child < 5 & child > 0 & republican == 1)
dem.cases <- subset(women_cases, child < 5 & child > 0 & republican == 0)
men.cases <- subset(women_cases, woman == 0)
womyn.cases <- subset(women_cases, woman == 1)


################ Party

my.outPARTY <- lm(lib_vote_share ~ I(girls > 0)*republican + as.factor(child), 
	data = judge_data, weights = judge_data$no_cases)
# summary(my.outPARTY)

## for republicans

my.outREP <- lm(lib_vote_share ~ I(girls > 0) + as.factor(child), 
	data = rep.means, weights = rep.means$no_cases)
# summary(my.outREP)


## for democrats

my.outDEM <- lm(lib_vote_share ~ I(girls > 0) + as.factor(child), 
	data = dem.means, weights = dem.means$no_cases)
# summary(my.outDEM)

################ Gender

## for men
	
my.outGENDER <- lm(lib_vote_share ~ I(girls > 0)*woman + as.factor(child), 
	data = judge_data, weights = judge_data$no_cases)
# summary(my.outGENDER)

## for men
	
my.outMEN <- lm(lib_vote_share ~ I(girls > 0) + as.factor(child), 
	data = men.means, weights = men.means$no_cases)
# summary(my.outMEN)

## for women

my.outWOMEN <- lm(lib_vote_share ~ I(girls > 0) + as.factor(child), 
	data = women.means, weights = women.means$no_cases)
# summary(my.outWOMEN)

my.outREPMEN <- lm(lib_vote_share ~ I(girls > 0) + as.factor(child), 
	data = subset(men.means, republican == 1), weights = men.means$no_cases[which(men.means$republican == 1)])
# summary(my.outREPMEN)


stargazer(my.outREP, my.outDEM, my.outMEN, my.outWOMEN, my.outREPMEN,
	style = "ajps", header = FALSE, omit.stat = c("f","ser"), dep.var.labels = "Share of Votes in Feminist Direction", digits = 2, covariate.labels = c("At Least 1 Girl", "2 Children", "3 Children", "4 Children","Constant"), title = "Weighted least squares results. Outcome is judges' proportion of feminist votes on gender-related cases. All models include fixed effects for total number of children and use weights based on the number of cases heard by each judge.", label = "t:results_party")

```
```{r, results="asis"}



```


```{r, results="asis"}


########################################################
## Table 8: Judges with 0 or 1 child
########################################################

## Including people who have zero children as a control 
## suggested by AJPS editor 
## (Note: Caution against making inferences on effect of
## daughters among people with 0 children)

my.out12 <- lm(lib_vote_share ~ I(girls > 0) + as.factor(child), 
	data = subset(judge_data, child < 2), 
		weights = judge_data$no_cases[which(judge_data$child < 2)])
# summary(my.out12)

my.out13 <- lm(lib_vote_share ~ I(girls > 0), 
	data = subset(judge_data, child == 1), 
		weights = judge_data$no_cases[which(judge_data$child == 1)])
# summary(my.out13)

## and then controlling for rep or dem:

my.out14 <- lm(lib_vote_share ~ I(girls > 0) + I(republican==1), 
	data = subset(judge_data, child == 1), 
		weights = judge_data$no_cases[which(judge_data$child == 1)])
# summary(my.out14)


stargazer(my.out12, my.out13, my.out14, header = FALSE, 
	style = "ajps", omit.stat = c("f","ser"), dep.var.labels = "Liberal Judge-Vote")





```
```{r, results="asis"}

########################################################
## Table 9: Distribution of gender-related cases
########################################################


## just republicans:
rep.means <- subset(judge_data, republican == 1)

## just democrats
dem.means <- subset(judge_data, republican == 0)



aa <- table(dem.means$child, dem.means$girl)
bb <- table(rep.means$child, rep.means$girl)

aa.1 <- prop.table(table(dem.means$child, dem.means$girl),1)
bb.1 <- prop.table(table(rep.means$child, rep.means$girl),1)

colnames(aa.1) <- c("0 Girls", "1 Girl", "2 Girls", "3 Girls", "4 Girls", "5 Girls")

colnames(bb.1) <- c("0 Girls", "1 Girl", "2 Girls", "3 Girls", "4 Girls")

xtable(cbind(aa.1, bb.1))
```


